### PR TITLE
Fix #52: Fixed parsing project and branch name from url string

### LINKED ISSUE #52: Issue with parsing branch name from url
After recent changes during parsing branch name that contains slash and is located in repository within namespace in subgroup there was an issue with parsing such a string from url.
For example this repository will not work on current version:

`namespace/subgroup/repository:feature/branch`

### PR DESCRIPTION
**Pull request by marek-ganko**
Upgrade dependency versions
Refactored Code for linter
Removed automatically generated files and added them to .gitignore

### CODE REVIEW

**Comment by emilianoeloi** [comment]
Hello, Marek. I believe we need to not ignore the standalone folder, only part of it is generated. Could you make that change?
Thank you.

Emiliano

**Comment by marek-ganko** [comment]
Hi Emiliano, thanks for pointing that out, I missed that index.js file :)
I placed it in the root dir and I'm copying it during the build process.

Now repository and npm package should be a lot smaller because you don't push previously generated files.

**Comment by emilianoeloi** [comment]
Nice, Marek. Thanks again

**Comment by emilianoeloi** [comment]
+ gitlab-ci-dashboard@6.1.0-alpha.1

**Pull request merged**
