### PR TITLE
Fix: Get last tag by name

### PR DESCRIPTION
**Pull request by necosta**
Hi, This is my first contribution to this repo so may need some help in getting this merged.

Not sure if you require the creation of a new issue but the selection of tags is currently returning the first element from GitLab API (curl -X GET http://GitLabHost/api/v4/projects/id/repository/tags) when it should be a little bit more smarter than that.

The approach I took was to select the latest tag by name which I think is a reasonable option.

Please review and let me know any questions.

### CODE REVIEW

**Comment by emilianoeloi** [comment]
Olá Sr. Costa. Thanks for your contribution!

**Comment by emilianoeloi** [comment]
+ gitlab-ci-dashboard@6.3.0-rc.1

**Comment by marek-ganko** [comment]
@necosta Did you check your solution with tags containing prefix like `v`?
It seems that library you used doesn't handle that properly: https://github.com/substack/semver-compare/issues/5
This issue points out that this library is not semver compatible and will not work properly with pre released versions: https://github.com/substack/semver-compare/issues/1

@necosta @emilianoeloi I think there should be more unit tests for those scenarios

**Comment by necosta** [comment]
Thanks! Improvements on https://github.com/emilianoeloi/gitlab-ci-dashboard/pull/63

**Pull request merged**
